### ISSUE TITLE
File name too long after make install on windows

### ISSUE THREAD

**Issue by kfoster19** [PolicyEngine/policyengine-api#1]
(base) PS C:\Users\Kevin\Documents\policyengine-api> make install
pip install -e .
Obtaining file:///C:/Users/Kevin/Documents/policyengine-api
  Preparing metadata (setup.py) ... done
Collecting policyengine_uk@ git+https://github.com/policyengine/policyengine-uk@policyengine-dev
  Cloning https://github.com/policyengine/policyengine-uk (to revision policyengine-dev) to c:\users\kevin\appdata\local\temp\pip-install-n3zx7ogc\policyengine-uk_17169ec21bfe49048596570357a65f04
  Running command git clone --filter=blob:none --quiet https://github.com/policyengine/policyengine-uk 'C:\Users\Kevin\AppData\Local\Temp\pip-install-n3zx7ogc\policyengine-uk_17169ec21bfe49048596570357a65f04'
  error: unable to create file policyengine_uk/tests/policy/baseline/gov/dwp/pension_credit/guarantee_credit/minimum_guarantee/additional/severe_disability_minimum_guarantee_addition.yaml: Filename too long
  fatal: unable to checkout working tree
  warning: Clone succeeded, but checkout failed.
  You can inspect what was checked out with 'git status'
  and retry with 'git restore --source=HEAD :/'

  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/policyengine/policyengine-uk 'C:\Users\Kevin\AppData\Local\Temp\pip-install-n3zx7ogc\policyengine-uk_17169ec21bfe49048596570357a65f04' did not run successfully.        
  │ exit code: 128
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/policyengine/policyengine-uk 'C:\Users\Kevin\AppData\Local\Temp\pip-install-n3zx7ogc\policyengine-uk_17169ec21bfe49048596570357a65f04' did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
make: *** [Makefile:2: install] Error 1
(base) PS C:\Users\Kevin\Documents\policyengine-api>

**Comment by anth-volk** [comment]
@nikhilwoodruff or @MaxGhenis

**Comment by nikhilwoodruff** [comment]
Thanks @anth-volk - that makes sense to me.
