### ISSUE TITLE
Incorrect budgetary impacts with state taxes

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#1041]
For example these numbers don't add up
https://policyengine.org/us/policy?focus=policyOutput.netIncome&reform=42964&region=nyc&timePeriod=2024&baseline=2

<img width="711" alt="image" src="https://github.com/PolicyEngine/policyengine-api/assets/6076111/e337758a-9e28-4f7c-89af-7154d36faefe">

@leogoldman fyi

**Comment by nikhilwoodruff** [comment]
Fixed now?
