### ISSUE TITLE
Failure loading a policy

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#1091]
Just now here: https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=43092&region=enhanced_us&timePeriod=2024&baseline=2

<img width="1340" alt="image" src="https://github.com/PolicyEngine/policyengine-api/assets/6076111/3a956b62-d11e-4e14-9959-209968987909">

**Comment by abhcs** [comment]
Worked for me but took a long time:

<img width="814" alt="Screenshot 2024-02-23 at 6 35 47 PM" src="https://github.com/PolicyEngine/policyengine-api/assets/31144719/9f09e0ff-7836-43e3-a01d-1552068ea6e4">

**Comment by abhcs** [comment]
The issue is intermittent and needs more investigation. I had trouble loading the page today; yet, when I refreshed the page loaded immediately, indicating that the result was cached on the cloud instance but not communicated to the front end properly.
