### ISSUE TITLE
Policy renaming isn't working

### ISSUE THREAD

**Issue by dotslashbit** [PolicyEngine/policyengine-api#1096]
At the moment, on the live app, when a user first creates a policy, one POST request is fired to the `/policy` endpoint, creating a record with an empty `label` value and an ID number. When a user first renames their policy, the app works half-correctly. If you check out the `set_policy` endpoint [here](https://github.com/PolicyEngine/policyengine-api/blob/master/policyengine_api/endpoints/policy.py), you'll see why this is: if a new request is made and a record with the `policy_hash` and `policy_id` already exist, then the app attempts to either pull the existing label or add the new one to the overall data structure (I'll come back to that in a moment). It then creates a new record with all the same information, then updates that information (perhaps that creates the weird duplicate record we're seeing?).

However, if the user attempts to change the name another time, this outright fails, as that label pull that I mentioned before finds that the record has an existing label, so just tosses the new one out.

I think the root of this problem is with the API–more specifically, its lack of care to follow RESTful principles. If this were RESTful, we'd use the POST request only to create records, and we'd have a separate UPDATE endpoint where we could merely update the `label` parameter, simplifying a lot of this headache, I'd think.

**Comment by anth-volk** [comment]
This should've been closed with #1144.
