### ISSUE TITLE
US cliff impact never completes

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#12]
Gets stuck on `Computing the cliff impact...`

https://beta.policyengine.org/us/policy?reform=12&focus=policyOutput.cliffImpact&region=us&timePeriod=2022&baseline=2

[Other US impacts work](https://beta.policyengine.org/us/policy?reform=12&focus=policyOutput.netIncome&region=us&timePeriod=2022&baseline=2), and [UK cliff impacts work](https://beta.policyengine.org/uk/policy?reform=83&focus=policyOutput.cliffImpact&region=uk&timePeriod=2022&baseline=1)

**Comment by nikhilwoodruff** [comment]
Looking into it - it's working on other reforms: 
<img width="1505" alt="image" src="https://user-images.githubusercontent.com/35577657/207072025-b00fa2c0-2d9b-4744-8862-2f772eb93930.png">

**Comment by nikhilwoodruff** [comment]
OK I think it's an issue with that reform specifically: I tried [changing 75% -> 76% and it worked](https://beta.policyengine.org/us/policy?reform=162&focus=policyOutput.cliffImpact&region=us&timePeriod=2022&baseline=2): 
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/35577657/207072845-e7f16b59-f225-4903-adac-8a4d52db8d8e.png">

**Comment by nikhilwoodruff** [comment]
Should be fixed now

**Comment by MaxGhenis** [comment]
What was the issue?
