### ISSUE TITLE
Update where the API sources the deployment Docker image from

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#1639]
At present, it uses the deprecated `nikhilwoodruff` Docker account. We've since shifted to the `policyengine` Docker account. This appears to be causing the API deployment failure.

**Comment by MaxGhenis** [comment]
We're still using it in the action:

https://github.com/PolicyEngine/policyengine-api/blob/a5f50cc32bcfddac5f5a9d8946257709b19ffee0/.github/workflows/pr.yml#L59

Can we change it? This is causing #1706 to fail, since it updates to Python 3.10 while the nikhilwoodruff one is 3.9.

**Comment by MaxGhenis** [comment]
Doing so seemed to work
