### ISSUE TITLE
API deployment still fails

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#1641]
Unclear what the cause of it is now

**Comment by MaxGhenis** [comment]
Claude suggested this after sharing the [failure](https://github.com/PolicyEngine/policyengine-api/actions/runs/9933590933/job/27436590873) and contents of gcp/policyengine_api/

---

Thank you for sharing your Dockerfile. I can see a few issues that might be causing the problem with `start.sh` not being found. Let's make some modifications to ensure everything is set up correctly:

1. Set the working directory:
   Add a WORKDIR instruction to set the working directory to `/app`.

2. Copy the start.sh file explicitly:
   Add a COPY instruction to copy the start.sh file to the correct location.

3. Set execute permissions on start.sh:
   Add a RUN instruction to make start.sh executable.

4. Use the full path in the CMD instruction:
   Update the CMD instruction to use the full path to start.sh.

Here's an updated version of your Dockerfile with these changes:

```dockerfile
FROM policyengine/policyengine-api:latest

ENV GOOGLE_APPLICATION_CREDENTIALS .gac.json
ENV POLICYENGINE_DB_PASSWORD .dbpw
ENV POLICYENGINE_GITHUB_MICRODATA_AUTH_TOKEN .github_microdata_token
ENV ANTHROPIC_API_KEY .anthropic_api_key
ENV OPENAI_API_KEY .openai_api_key

WORKDIR /app

# Copy the entire application
ADD . /app

# Copy start.sh explicitly
COPY policyengine_api/gcp/policyengine_api/start.sh /app/start.sh

# Make start.sh executable
RUN chmod +x /app/start.sh

# Install dependencies and run tests
RUN make install && make test

# Use the full path to start.sh
CMD ["/bin/sh", "/app/start.sh"]
```

These changes should help ensure that `start.sh` is in the correct location and is executable when the container starts.

Additionally, make sure that the path to `start.sh` in the COPY instruction matches its actual location in your project structure. If the path is different, adjust it accordingly.

After making these changes, rebuild your Docker image and try deploying again. If you're still encountering issues, you may need to check the Google Cloud Build logs for more detailed information about the deployment process. You can access these logs using the Google Cloud Console or by running:

```
gcloud app logs read
```

This will give you more detailed information about what's happening during the deployment and startup process, which can help identify any remaining issues.
