### ISSUE TITLE
Deploying API exceeds CPU quota

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#177]
I tried retrying but it didn't work. This is blocking deployments.

https://github.com/PolicyEngine/policyengine-api/actions/runs/4154248138/jobs/7186563968#step:7:43

> ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: The following quotas were exceeded: CPUS (quota: 24, used: 24 + needed: 4), IN_USE_ADDRESSES (quota: 8, used: 8 + needed: 1).

Some suggestions at https://stackoverflow.com/questions/43656886/google-app-engine-error-gcloud-app-deploy-invalid-argument-the-following-quo

**Comment by nikhilwoodruff** [comment]
Retrying- I think they were just too slow to shut down previous versions

**Comment by MaxGhenis** [comment]
Thanks, that one ran
