### ISSUE TITLE
Remove get_search endpoint

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#1795]
This actually appears to be by design. If it isn't, this would need to be fixed - appears to be an issue with Hugging Face embeddings. If it is by design, it needs to be documented.

**Comment by nikhilwoodruff** [comment]
I'd be open to removing it for now- it comes with heavy dependencies (`torch`) that probably add minutes to the install time and we don't currently use it much.

**Comment by anth-volk** [comment]
@nikhilwoodruff What do we use it for?

**Comment by nikhilwoodruff** [comment]
Nothing in the app at the moment- it was intended for a streamlit app that powered a chat interface.

**Comment by anth-volk** [comment]
@tawandamoyo Would you be willing to take this on? And additionally, if `torch` is required in `setup.py`, could you check that it's not imported elsewhere, then attempt to remove it?

**Comment by nikhilwoodruff** [comment]
Torch is required by sentence-transformers
