### ISSUE TITLE
Migrate `metadata` endpoint to new API structure

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#1992]

**Comment by mikesmit** [comment]
Picking this up now. Anthony provided the following files as examples to follow:
* https://github.com/PolicyEngine/policyengine-api/blob/master/policyengine_api/routes/tracer_analysis_routes.py
* https://github.com/PolicyEngine/policyengine-api/blob/master/policyengine_api/routes/simulation_analysis_routes.py

**Comment by mikesmit** [comment]
Went ahead and did a straight implementation, but had the following additional notes to discuss with Anthony:
1. I think blueprints want us to flatten our REST structure. You can have blueprints overlap paths (I.e. multiple blueprints can add to <country>/...), but if you accidentally add the same route twice, it just picks the second one. The general pattern should be each entity is it's own blueprint (now maybe in this case the entity is country, not metadata, but probably we should reorganize)
2. The test organization is interesting. Usually I would have a unit test per class, one class per file. Are we interested in adding more granularity
3. inconsistent use of types: some things use types others don't.. metadata is a dict (not Dict[...]), some code declares types for inputs, but not for return values, etc. etc. Used what is there, but suggest we clean that up.

**Comment by anth-volk** [comment]
Thanks for taking this on, Mike. I'd love to discuss this more in-depth, perhaps face-to-face, but here are my initial thoughts in response to your points:

1. The way that we use the `country_id` value, I would argue that `country` is not sufficiently independent of any subsequent operations to be considered its own entity. Now, is that the _correct_ way to treat it? I think that's up for debate.
2. I do have a PR open (https://github.com/PolicyEngine/policyengine-api/pull/2021) that aims to make a first attempt at moving to an improved testing structure, with a view toward iteratively improving the structure after that point. That said, I'd love to chat more about this, as my own knowledge of testing best practices is limited.
3. Very true, typing is inconsistent throughout. This is something I've been looking to iteratively improve upon as we migrate to this.
