### ISSUE TITLE
AI summary broken

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#1995]
On both household and reform summaries.

Endless GENERATING... [here](https://policyengine.org/us/policy?focus=policyOutput.analysis&household=49593&region=enhanced_us&timePeriod=2024&baseline=2&reform=70203)

Empty explanation [here](https://policyengine.org/us/household?focus=householdOutput.netIncome&household=38803)
<img width="992" alt="image" src="https://github.com/user-attachments/assets/62fa6ad9-4618-4782-8469-344182524fbf">

I just checked our Anthropic console and we don't have any billing issues or anything.

**Comment by anth-volk** [comment]
Update on this: Looks to be caused by this:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.policyengine.org/us/simulation-analysis. (Reason: CORS request did not succeed). Status code: (null).
```

Will investigate further locally.
