### ISSUE TITLE
Add `{"country": COUNTRY_ID }` as key-value pair to the metadata

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#2031]
I realize that most of the time, we know what the country ID is because we're fetching the metadata using it, but there are a few cases where the code actually doesn't (particularly helper functions within the React app), and so we should add it as a top-level key-value pair

**Comment by HerveRI** [comment]
We're currently using the country ID to fetch the metadata from the backend, then merging the retrieved response, manipulating certain fields, and appending country-specific details using country ID. Moving forward, we could consider consolidating this metadata construction into a single location for better clarity and maintainability.

**Comment by anth-volk** [comment]
@HerveRI Would you mind also opening an issue in this repo indicating that we should reconsider how we handle metadata to try to prevent it being constructed in both the back end and front end?

**Comment by HerveRI** [comment]
The create issue: https://github.com/PolicyEngine/policyengine-api/issues/2078
