### ISSUE TITLE
Update APIs concurrently

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-api#210]
Currently, each API update leaves the population impacts broken for 20 minutes because the compute API is updated sequentially after the main API. We could update them both concurrently.

**Comment by MaxGhenis** [comment]
Does this being closed mean we no longer have dead time after updating the API?

**Comment by nikhilwoodruff** [comment]
It's no longer guaranteed 20m dead time, yes. But I just noticed one of the actions failed, seems to be a simpler timeout issue.
