### ISSUE TITLE
Upgrade to Environment Files

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#229]
We get the following warning on our actions ([example](https://github.com/PolicyEngine/policyengine-api/actions/runs/4351629443)):
>The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

**Comment by anth-volk** [comment]
@nikhilwoodruff I'd be happy to take this on, but may request some backup from those better versed in Python

**Comment by nikhilwoodruff** [comment]
Thanks @anth-volk! Yes feel free
