### ISSUE TITLE
Fix local database flag

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#24]
Causing https://github.com/PolicyEngine/policyengine-app/issues/92

**Comment by MaxGhenis** [comment]
Oh so this was introduced [here](https://github.com/PolicyEngine/policyengine-api/pull/21/files#diff-c38b2e0449fb5dc6ac13ff8a55f90ebbdc84d63523b2e83262e839d51e48f311R263), where `local=True`, but it's back to False now:

https://github.com/PolicyEngine/policyengine-api/blob/e165683a813d602f18efa54eb90ab1aced123d98/policyengine_api/data/data.py#L263

Has it not deployed or is there another issue?

**Comment by nikhilwoodruff** [comment]
Yeah, the deployment failed
