### ISSUE TITLE
Fix Gini impact in some State simulations

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-api#347]
In some states, the Gini impact calculation was throwing an error so I disabled it (where it errors).

**Comment by anth-volk** [comment]
Happy to investigate this over the coming week

**Comment by nikhilwoodruff** [comment]
Thanks @anth-volk!

**Comment by anth-volk** [comment]
Hey @nikhilwoodruff, I've been going through the API trying to figure out this issue, and I'm wondering if it traces back to policyengine-core or one of the country packages. On line 15 of the api package's single_economy.py ([here](https://github.com/PolicyEngine/policyengine-api/blob/c4f5f9dc4252e9fd535e2d03ab40a2519ae1c5e2/policyengine_api/endpoints/economy/single_economy.py#L9)), do you know what the source of the `gini()` method is? I can't seem to find a definition in the `Simulation` class definition in policyengine-core, the `calculate()` (or `_calculate()`) methods in the same package, or the `equiv_household_net_income` variable definition in policyengine-us or policyengine-uk. I also didn't see it defined in the numpy docs anywhere.

**Comment by nikhilwoodruff** [comment]
Hey @anth-volk - yes this is a little cryptic and we should probably add more type hints. But if you follow the `Microsimulation.calculate` function to its [definition](https://github.com/PolicyEngine/policyengine-core/blob/master/policyengine_core/simulations/microsimulation.py) in `policyengine-core`, it actually returns a `microdf.MicroSeries` instance (definition for `MicroSeries.gini` [here](https://github.com/PSLmodels/microdf/blob/master/microdf/generic.py#L124)).

That said, I haven't actually seen this error come up recently- my guess is that it's caused by some of the household net incomes being `None` which would cause the `gini` function to blow up. We did have an issue with that in `policyengine-us` a while ago, but AFAICT it's been fixed. So I think we could close this unless you've been able to reproduce it recently? (sorry for the effort on your part if so!)

**Comment by anth-volk** [comment]
Ah, thank you for the details @nikhilwoodruf , I suppose I should've followed the "paper trail" a bit more. Due to the installation issues I told you about in Slack, I've actually yet to get to test whether or not I could reproduce the issue. If you'd like, once I can get a local install up and running, I could test and see if I can reproduce it, but also if you feel confident enough, perhaps we could close? Sorry for all the installation issues on my end.

**Comment by anth-volk** [comment]
Hey @nikhilwoodruff, I've yet to reproduce this bug. Maybe it would be worthwhile to close until it resurfaces?

**Comment by nikhilwoodruff** [comment]
Thanks, yep closing.
