### ISSUE TITLE
get_search doesn't properly handle malformed type query parameter

### ISSUE THREAD

**Issue by anth-volk** [PolicyEngine/policyengine-api#421]
Similar to the issue with malformed `country_id` parameters, if a user accesses the `get_search` endpoint and inputs a malformed `type` query parameter, the endpoint returns with a `500 Internal Server Error`, as opposed to some sort of error response (perhaps `400 Bad Request`?), because the function raises a ValueError when the error is encountered

**Comment by anth-volk** [comment]
This is due to code on line 87 of `endpoints/search/search.py`; if an empty query is passed, the server throws an AttributeError, as the query has no attribute 'lower', returning a 500 Internal Server Error

**Comment by tawandamoyo** [comment]
closed by #1795 which removed the `get_search` endpoint
