### ISSUE TITLE
Error with NYC household

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#470]
[Single person with $500k wages in NYC](https://policyengine.org/us/household?focus=householdOutput.netIncome&household=31104) is only showing up with NY tax, no NYC tax:

<img width="877" alt="image" src="https://github.com/PolicyEngine/policyengine-api/assets/6076111/ba65d28d-c9b0-4460-bc65-fcdec4510251">

[Earnings variation chart](https://policyengine.org/us/household?focus=householdOutput.earnings&household=31104) crashes:
<img width="821" alt="image" src="https://github.com/PolicyEngine/policyengine-api/assets/6076111/8efc05b5-e840-4fd5-9a99-743964403ac4">

Similar failures for a [single NYC resident with $0 earnings](https://policyengine.org/us/household?focus=householdOutput.netIncome&household=31108).

Filing here as NYC taxes are correctly computed in Colab: https://colab.research.google.com/drive/1g9_jX97XEuEaJRPnqBE2S9DF5JAYnQHL?usp=sharing

The app computed NYC taxes correctly as recently as a few days ago, so might be Python 3.10.

**Comment by nikhilwoodruff** [comment]
OK it's because of the NY CDCC dividing by zero.
