### ISSUE TITLE
API endpoint for LLM Q&A

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#508]
From https://github.com/policyengine/policyengine-chat

**Comment by anth-volk** [comment]
@MaxGhenis To be clear, at the moment, this is essentially moving the AI policy analysis logic that we use on the front end to the back end and making it its own endpoint?

**Comment by anth-volk** [comment]
Would we still want to display the prompt on the front end? That may be why the logic sits there at the moment.

**Comment by MaxGhenis** [comment]
Sure

**Comment by anth-volk** [comment]
That would require either having the front end fetch the prompt and the AI output, or leaving the logic on the front end, it would seem to me

**Comment by MaxGhenis** [comment]
Let's write the prompt to the db
