### ISSUE TITLE
US population impacts take almost two minutes

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#65]
I just ran three population impacts, each of which took longer than usual. I timed the [last one](https://beta.policyengine.org/us/policy?focus=policyOutput.povertyImpact&reform=14&region=md&timePeriod=2022&baseline=2) at 1:50.

**Comment by nikhilwoodruff** [comment]
Feel free to reopen but now usually takes around 20 seconds
