### ISSUE TITLE
Re-add `earned_income_tax_credit` variable for legacy API calls

### ISSUE THREAD

**Issue by nikhilwoodruff** [PolicyEngine/policyengine-api#870]
After an API user reported broken call results.

**Comment by martinholmer** [comment]
@nikhilwoodruff provided this as the rationale for adding a duplicate variable:
> After an API user reported broken call results.

This project is not at 1.0.0+ version, so API users expect changes in the API.
Why was this not resolved by the user changing the code that calls the API?

**Comment by MaxGhenis** [comment]
We have also requested the API user to change their code. Even at version 0.x, we should issue deprecation warnings for some period before substantially changing the API. That oversight was my error in reviewing the PR.
