### ISSUE TITLE
Poverty and deep poverty impacts don't respect US state

### ISSUE THREAD

**Issue by MaxGhenis** [PolicyEngine/policyengine-api#88]
For example, this reform produces identical results in [Maryland](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&region=md&timePeriod=2023&baseline=2&reform=89&household=62), [Florida](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&region=fl&timePeriod=2023&baseline=2&reform=89&household=62), and [US](https://policyengine.org/us/policy?focus=policyOutput.povertyImpact&region=us&timePeriod=2023&baseline=2&reform=95&household=62). @ngpsu22

**Comment by nikhilwoodruff** [comment]
Now fixed
